<a href="https://colab.research.google.com/github/majagurdek/Machine-Learning/blob/main/lab7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_openml

In [ ]:
mnist = fetch_openml('mnist_784', version=1, as_frame=False)
mnist.target = mnist.target.astype(np.uint8)
X = mnist["data"]
y = mnist["target"]

In [ ]:
#klasteryzacja

In [ ]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [ ]:
kmeans_sil = []

In [ ]:
kmeans8 = KMeans(n_clusters=8).fit(X)
kmeans_sil.append(silhouette_score(X, kmeans8.labels_))

In [ ]:
kmeans9 = KMeans(n_clusters=9).fit(X)
kmeans_sil.append(silhouette_score(X, kmeans9.labels_))

In [ ]:
kmeans10 = KMeans(n_clusters=10).fit(X)
kmeans_sil.append(silhouette_score(X, kmeans10.labels_))

In [ ]:
kmeans11 = KMeans(n_clusters=11).fit(X)
kmeans_sil.append(silhouette_score(X, kmeans11.labels_))

In [ ]:
kmeans12 = KMeans(n_clusters=12).fit(X)
kmeans_sil.append(silhouette_score(X, kmeans12.labels_))

In [ ]:
import pickle

In [ ]:
with open('kmeans_sil.pkl', 'wb') as f:
    pickle.dump(kmeans_sil, f, pickle.HIGHEST_PROTOCOL)

In [ ]:
with open('kmeans_sil.pkl', 'rb') as f:
    print(pickle.load(f))

[0.07336530737826967, 0.0568164685794118, 0.05628448814090457, 0.05834363268351162, 0.05819727577736494]


In [ ]:
#macierz bledow

In [ ]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(y, kmeans10.predict(X))
matrix

array([[  44,  624,   29,  286,    0,   15, 5499,  264,  105,   37],
       [  10,    7,    7,   11, 4369,    8,    0,   11,    3, 3451],
       [4902,  157,   75,  456,  369,   45,   75,  175,  270,  466],
       [ 261, 1381,   42, 4592,  417,  180,   37,   66,   69,   96],
       [  17,   13, 1785,    0,  112, 1933,    4,  150, 2537,  273],
       [  21, 2161,  327, 2067,  131,  358,   69,  154,  207,  818],
       [  79,  163,    1,   35,  275,    4,   90, 5281,  720,  228],
       [  42,    4, 3374,    3,  246, 2711,   14,    4,  603,  292],
       [  50, 3670,  261, 1598,  293,  254,   36,   61,  153,  449],
       [   5,   56, 1995,   92,  147, 2977,   38,   10, 1550,   88]])

In [ ]:
ind = np.argmax(matrix, axis=-1)
ind

array([6, 4, 0, 3, 8, 1, 7, 2, 1, 5])

In [ ]:
ind2 = np.unique(ind)
ind2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
with open('kmeans_argmax.pkl', 'wb') as f:
    pickle.dump(ind2, f, pickle.HIGHEST_PROTOCOL)

In [ ]:
with open('kmeans_argmax.pkl', 'rb') as f:
    print(pickle.load(f))

[0 1 2 3 4 5 6 7 8]


In [ ]:
#DBSCAN

In [ ]:
dist = []

for i in range(300):
    for j in X:
        if not ((X[i]==j).all()):
          dist.append(np.linalg.norm(X[i] - j))

In [ ]:
dist_s = np.unique(dist)[:10]
dist_s

array([279.26152617, 304.3764117 , 317.5893575 , 328.76587414,
       333.45464459, 352.89800226, 355.17742045, 358.0740147 ,
       359.64287842, 360.42474943])

In [ ]:
with open('dist.pkl', 'wb') as f:
    pickle.dump(dist_s, f, pickle.HIGHEST_PROTOCOL)

In [ ]:
with open('dist.pkl', 'rb') as f:
    print(pickle.load(f))

[279.26152617 304.3764117  317.5893575  328.76587414 333.45464459
 352.89800226 355.17742045 358.0740147  359.64287842 360.42474943]


In [ ]:
s  = (dist_s[0]+dist_s[1]+dist_s[2])/3
s

300.40909845916684

In [ ]:
from sklearn.cluster import DBSCAN
db_len = []

In [ ]:
# dbscan1 = DBSCAN(eps=s)
# dbscan1.fit(X)
# db_len.append(len(set(dbscan1.labels_)))

# dbscan2 = DBSCAN(eps=1.04*s)
# dbscan2.fit(X)
# db_len.append(len(set(dbscan2.labels_)))

# dbscan3 = DBSCAN(eps=1.08*s)
# dbscan3.fit(X)
# db_len.append(len(set(dbscan3.labels_)))

In [ ]:
for i in (s, 1.04*s, 1.08*s):
   dbscan = DBSCAN(eps=i)
   dbscan.fit(X)
   db_len.append(len(set(dbscan.labels_)))

In [ ]:
with open('dbscan_len.pkl', 'wb') as f:
    pickle.dump(db_len, f, pickle.HIGHEST_PROTOCOL)

In [ ]:
with open('dbscan_len.pkl', 'rb') as f:
    print(pickle.load(f))

[4, 7, 22]
